### PR TITLE
refactor: remove nimbaser and nim-base32 dependencies, use stew modules in their place

### PR DESCRIPTION
**Pull request by michaelsbradleyjr**
Closes issue #56.

---

~~I think these changes are correct, but I would appreciate some review/feedback to check that `.replace("=", "")` is no longer necessary.~~

~~I did not implement any new/additional error checking re: [`stew/base32.encode`'s `Base32Status.Overrun`](https://github.com/status-im/nim-stew/blob/master/stew/base32.nim#L137-L142).~~

See also https://github.com/status-im/status-desktop/pull/3731 and https://github.com/status-im/status-desktop/issues/1268.

---

I realized when working on fixes re: @richard-ramos' PR review  that we're relying on `vendor/nimbaser` for `base58`. I've now revised the PR so that `nimbaser` is dropped in addition to dropping `nim-base32`. In `nimbaser`'s place, I've substituted `stew/base58`.

I had a previous question re: whether `.replace("=", "")` is still necessary. It's not necessary because from `stew/base32` I've used [`base32.Base32Lower`](https://github.com/status-im/nim-stew/blob/master/stew/base32.nim#L25-L26). The comment for that type includes `without padding`, which means no `=` will be used.

When switching from `nimbaser` to `stew/base58`, there's a question of alphabet. As far as I can tell `nimbaser` is [using the Bitcoin alphabet](https://github.com/D-Nice/nbaser/blob/master/src/nbaser.nim#L182). So from `stew/base58` I've used [`base58.BTCBase58`](https://github.com/status-im/nim-stew/blob/master/stew/base58.nim#L23-L24).

### CODE REVIEW

**Review by richard-ramos — CHANGES_REQUESTED** [review]
Using base32:
```nim
echo base32.encode(string.fromBytes(base58.decode( "QmXGPD8y5MwujTGG5B2wWCYZewt4QTc88E8N99uBDiUKUk"    ))).toLowerAscii().replace("=", "")

#expected value:
ciqijikvoshjks53x6kw3wo47gvfo3pso72bnzph7janzqiuszqyjgi
```

However, with this change, i get an empty seq[char]
```nim
 var
        base32Hash: seq[char]
        base32HashLen: int

discard base32.encode(base32.HexBase32Lower,
        base58.decode("QmXGPD8y5MwujTGG5B2wWCYZewt4QTc88E8N99uBDiUKUk"), base32Hash, base32HashLen)
echo base32Hash
```

**Comment by michaelsbradleyjr** [comment]
> However, with this change, i get an empty seq[char]

Thanks! I guess I missed something, will check it tomorrow and make another commit.

**Comment by michaelsbradleyjr** [comment]
I'm guessing `base32HashLen: int` has to already equal the expected length of the `seq` or effectively nothing gets written  to the `var`.

**Comment by michaelsbradleyjr** [comment]
I checked that with the revisions I've just made, I now generate the expected base32 hash `ciqijikvoshjks53x6kw3wo47gvfo3pso72bnzph7janzqiuszqyjgi`.

**Review by richard-ramos — APPROVED** [review]

**Pull request merged**
